#!/bin/bash

# System configs
alias src="vim ~/.zshrc && omz reload"
alias brc="vim ~/.bashrc && source ~/.bashrc"
alias vrc="vim ~/.vimrc"
alias aliascfg="vim ~/.aliases && omz reload"
alias i3rst="i3-msg restart"
alias i3config="vim ~/.config/i3/config"
alias explorer="xdg-open"

# ls variations
alias l='ls -lah'
alias l.='ls -d .* --color=auto'
alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls --color=tty'
alias lsa='ls -lah'

# Others
alias arduino="~/Downloads/arduino-ide_nightly-20240507_Linux_64bit.AppImage &"
