#!/bin/bash

alias src="vim ~/.zshrc && omz reload"
alias brc="vim ~/.bashrc && source ~/.bashrc"
alias vrc="vim ~/.vimrc"
alias i3rst="i3-msg restart"
alias i3config="vim ~/.config/i3/config"
alias explorer="thunar"

alias l='ls -lah'
alias l.='ls -d .* --color=auto'
alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls --color=tty'
alias lsa='ls -lah'
