import = ["/home/liveuser/.config/alacritty/themes/gruvbox-dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
# blink_interval = 300
# blink_timeout = 0
blinking = "On"
# shape = "Block"

[font]
size = 11

[font.bold]
# family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
# family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
# family = "JetBrains Mono"
style = "Italic"

[font.normal]
# family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[shell]
program = "/usr/bin/zsh"

[scrolling]
history = 20000
multiplier = 3

[window]
opacity = 0.86
title = "terminal"

[window.dimensions]
columns = 78
lines = 24

[window.padding]
x = 10
y = 10
